"""Emit the JMET revision Table 1 (cohort summary) from the n=50 cohort YAML.

Usage::

    uv run python scripts/build_cohort_table.py \\
        --cohort-yaml configs/cohort_ucsfpdgm_n50.yaml \\
        --metadata-csv data/UCSF-PDGM-metadata_v5.csv \\
        --out-tex outputs/tables/table1_cohort_summary.tex \\
        --out-csv outputs/tables/table1_cohort_per_subject.csv

The TeX output is plain ``\\begin{tabular}`` / ``\\end{tabular}`` (no
``\\begin{table}`` wrapper) so it can be ``\\input{}``-ed directly into
``paper/main.tex``. The per-subject CSV is the auditable backing
for the manuscript table; both files are git-ignored under ``outputs/``.

"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

from hpgs.io import cohort_summary, load_cohort_metadata


def _format_summary_tex(summary: dict, n_subjects: int) -> str:
    """Render the small Table 1 summary as a self-contained tabular block."""
    age = summary["age_years"]
    os_d = summary["os_days"]

    def _kv(d: dict, order: list[str] | None = None) -> str:
        keys = order if order is not None else sorted(d, key=str)
        parts = [f"{k}: {d[k]}" for k in keys if k in d]
        return ", ".join(parts) if parts else "--"

    sex_line = _kv(summary["sex"], order=["F", "M"])
    os_tertile_line = _kv(summary["os_tertile"], order=["short", "mid", "long"])
    mgmt_line = _kv(summary["mgmt_status"])
    eor_line = _kv(summary["eor"])
    vital_line = _kv({str(k): v for k, v in summary["vital_dead"].items()})
    brats_line = _kv(summary["brats21_segmentation_cohort"])

    rows = [
        ("Subjects (n)", f"{n_subjects}"),
        ("Sex", sex_line),
        (
            "Age at MRI (years)",
            f"median {age['median']:.0f}; mean {age['mean']:.1f}; "
            f"range [{age['min']:.0f}, {age['max']:.0f}]",
        ),
        (
            "Overall survival (days)",
            f"median {os_d['median']:.0f}; range [{os_d['min']:.0f}, {os_d['max']:.0f}]",
        ),
        ("OS tertile (short / mid / long)", os_tertile_line),
        ("MGMT status", mgmt_line),
        ("Extent of resection (EOR)", eor_line),
        ("Vital status (1=dead, 0=alive)", vital_line),
        ("BraTS21 segmentation cohort", brats_line),
    ]

    tex_lines = [
        "% Auto-generated by scripts/build_cohort_table.py — do not edit by hand.",
        "\\begin{tabular}{l l}",
        "\\hline",
        "\\textbf{Field} & \\textbf{Value} \\\\",
        "\\hline",
    ]
    for label, value in rows:
        tex_lines.append(f"{label} & {value} \\\\")
    tex_lines.append("\\hline")
    tex_lines.append("\\end{tabular}")
    return "\n".join(tex_lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    repo_root = Path(__file__).resolve().parent.parent
    parser.add_argument(
        "--cohort-yaml",
        type=Path,
        default=repo_root / "configs" / "cohort_ucsfpdgm_n50.yaml",
    )
    parser.add_argument(
        "--metadata-csv",
        type=Path,
        default=repo_root / "data" / "UCSF-PDGM-metadata_v5.csv",
    )
    parser.add_argument(
        "--out-tex",
        type=Path,
        default=repo_root / "outputs" / "tables" / "table1_cohort_summary.tex",
    )
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=repo_root / "outputs" / "tables" / "table1_cohort_per_subject.csv",
    )
    args = parser.parse_args(argv)

    cm = load_cohort_metadata(args.cohort_yaml, args.metadata_csv)
    summary = cohort_summary(cm)

    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_csv.parent.mkdir(parents=True, exist_ok=True)

    args.out_tex.write_text(_format_summary_tex(summary, n_subjects=cm.n))

    per_subject_cols = [
        "Sex",
        "Age at MRI",
        "WHO CNS Grade",
        "Final pathologic diagnosis (WHO 2021)",
        "MGMT status",
        "MGMT index",
        "IDH",
        "1-dead 0-alive",
        "OS",
        "OS_tertile",
        "EOR",
        "Biopsy prior to imaging",
        "BraTS21 ID",
        "BraTS21 Segmentation Cohort",
    ]
    cols = [c for c in per_subject_cols if c in cm.df.columns]
    out_df: pd.DataFrame = cm.df[cols].copy()
    out_df.index.name = "subject_id"
    out_df.to_csv(args.out_csv)

    print(f"[ok] wrote {args.out_tex} (n={cm.n}; seed={cm.seed})")
    print(f"[ok] wrote {args.out_csv}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
